version: "2"

services:
  app:
    build: .
    image: amber-moon
    command: amber watch
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/amber_moon_development
      REDIS_PROVIDER: REDIS_PROVIDERR
      REDIS_PROVIDERR: redis://redis:6379/0
    ports:
      - 3000:3000
    links:
      - db
      - redis
    volumes:
      - .:/app
      - nodes:/app/node_modules
      - shards:/app/lib

  migrate:
    build: .
    image: amber-moon
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && amber db migrate seed'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/amber_moon_development
    volumes:
      - .:/app
    links:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amber_moon_development
    volumes:
      - db:/var/lib/postgres/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    links:
      - db:db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.user
      PGADMIN_DEFAULT_USER: user
      PGADMIN_DEFAULT_PASSWORD: user
    ports:
      - "8080:80"
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

volumes:
  db:
  nodes:
  shards:
